version: "3.8"

services:
  app:
    build: .
    container_name: quark-dp-backend
    restart: unless-stopped
    environment:
      - PORT=8000
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
      - TZ=America/New_York

networks:
  default:
    external:
      name: nginx-network
